server:
  port: 8080


custom:
  jwt:
    secret: KrzQ!XYo%LVm1Igi7SUdh!8Xss7rz63BCyJlDZsq!1WFe0qqJJvsl%4Rt4DWgke
    iss: xdmdpz
    sub: RestQuickFramework
    expire-in-minute: 30
    header-name: token
  upload:
    zimg: http://127.0.0.1:4869
    file: /tmp/upload/file

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/example?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  jpa:
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
    time-zone: GMT+8
  data:
    web:
      pageable:
        default-page-size: 20
        page-parameter: page
        size-parameter: size

log4j:
  appender:
    system:
      out: org.apache.log4j.ConsoleAppender
      out.layout: org.apache.log4j.PatternLayout
    thisProject:
      file:
        out: org.apache.log4j.DailyRollingFileAppender
        out.File: logContentFile.log
        out.layout: org.apache.log4j.PatternLayout
  logger:
    thisProject:
      file: INFO,thisProject.upload.out
  rootLogger: INFO,system.out
