server:
  port: 8080


custom:
  upload:
    zimg: http://127.0.0.1:4869
    file: /tmp/upload/file

spring:
    datasource:
#        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123
#h2初始化配置
        url: jdbc:h2:mem:db_users;MODE=MYSQL;
        schema: classpath:sql/schema.sql
        data: classpath:sql/data.sql
        driver-class-name: org.h2.Driver

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

    jpa:
        database: h2
        generate-ddl: false
        hibernate:
          ddl-auto: update
        show-sql: true
    jackson:
        serialization:
            write-dates-as-timestamps: true
        time-zone: GMT+8
    data:
      web:
        pageable:
          default-page-size: 20
          page-parameter: page
          size-parameter: size




mybatis:
  type-aliases-package: com.yf.modules.dimain

mapper:
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

log4j:
    appender:
        system:
            out: org.apache.log4j.ConsoleAppender
            out.layout: org.apache.log4j.PatternLayout
        thisProject:
            file:
                out: org.apache.log4j.DailyRollingFileAppender
                out.File: logContentFile.log
                out.layout: org.apache.log4j.PatternLayout
    logger:
        thisProject:
            file: INFO,thisProject.upload.out
    rootLogger: INFO,system.out
